version: '3'
services:

  database: 
    image: postgres:12.9-bullseye
    container_name: leetleader-postgres
    ports: 
     - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./dev/configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=leetleader
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped
  
volumes:
  postgres-data:

networks:
  opensearch-net:

